server:
  port: 8080
spring:
  application:
    name: hospital_info_system
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/hospital_info_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456

  #主从库配置，主库负责增删改，从库负责查询，缓解数据库压力
  shardingsphere:
    datasource:
      names:
        master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.179.139:3306/hospital_info_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.179.140:3306/hospital_info_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    masterslave:
      #读写分离机制
      load-balance-algorithm-type: round_robin #轮询
      #最终的数据源名称
      name: dataSource
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true #显示sql，方便查看查库的情况
  main:
    allow-bean-definition-overriding: true #允许数据连接池覆盖，必须要这个配置，否则报错
  redis:
    host: localhost
    port: 6379
    database: 0
    password: foobared
  cache:
    redis:
      time-to-live: 1800000  #radis缓存有效期

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# 设备图片的存放路径
reggie:
  basePath: D:/totalStudy/sixth/MysqlPractice/img/
